version: '3.8'
services:
  node-api:
    container_name: node-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://prisma:root@postgres:5432/mydb?schema=mydb&sslmode=prefer

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: node-db

